In [45]:
# Load Library

import pandas as pd
from pathlib import Path

DATA_FOLDER_FILE = Path('../../data/')
print(f"Data folder path: {DATA_FOLDER_FILE}")

Data folder path: ..\..\data

In [46]:
# Load the dataset
INPUT_PATH = Path(DATA_FOLDER_FILE / 'raw/main_data.csv')

df = pd.read_csv(INPUT_PATH, low_memory=False)
df.head()

,ID,Journal,ISSN,Title,Authors,Year,Volume,Issue,Institution,Keywords,Abstrak,Abstract,Introduction,Method,Result,Discussion,Result & Discussion,Conclusion
0,2541-3279-1,Edulibinfo,2541-3279,HUBUNGAN ANTARA PROMOSI PERPUSTAKAAN MELALUI M...,Dellia Pavillo Aribah; Rudi Susilana; Hada Hid...,2014,1,1,Universitas Pendidikan Indonesia; Universitas ...,Libraries; Library Promotion; Wall Magazine; V...,Penelitian ini dilatarbelakangi oleh perkemban...,This research is motivated by the development ...,Kehidupan adalah suatu proses yang dinamis dan...,Metode yang digunakan dalam penelitian ini ada...,NaN,NaN,Permasalahan yang ingin dijawab dalam peneliti...,Berdasarkan perolehan data dari penelititan pe...
1,2541-3279-2,Edulibinfo,2541-3279,HUBUNGAN ANTARA PENGGUNAAN SEARCH FEATURES e-J...,Hana Wandari; Dinn Wahyudin; Damayanty,2014,1,1,Universitas Pendidikan Indonesia; Universitas ...,Search Features e-Journals; information needs,Penelitian ini membahas hubungan antara penggu...,This research explain the relationship between...,Perpustakaan memiliki fungsi sebagai Sumber in...,Penelitian hubungan penggunaan search features...,NaN,NaN,Pembahasan hasil penelitian dilakukan untuk me...,Berdasarkan hasil penelitian yang telah dilaku...
2,2541-3279-3,Edulibinfo,2541-3279,HUBUNGAN ANTARA KETERSEDIAAN FASILITAS PERPUST...,Iis Aprianti; Rudi Susilana; Hada Hidayat Margana,2014,1,1,Universitas Pendidikan Indonesia; Universitas ...,Library facility; interests visit,Penelitian ini membahas hubungan antara keters...,This research explain the relationship between...,Perpustakaan merupakan sebuah institusi pengel...,Penelitian hubungan ketersediaan fasilitas per...,NaN,NaN,Pembahasan hasil penelitian dimaksudkan untuk ...,Hasil penelitian yang telah dilakukan menunjuk...
3,2541-3279-4,Edulibinfo,2541-3279,PENGARUH KINERJA TERHADAP LAYANAN PRIMA DI CEN...,Masitoh Hamdayani; Dinn Wahyudin; Euis Rosinar,2014,1,1,Universitas Pendidikan Indonesia; Universitas ...,Libraries; Library Promotion; Wall Magazine; V...,Masalah yang menjadi kajian dalam penelitian a...,This research is motivated by the development ...,Gudang buku dengan penataan dan pengelolaan as...,NaN,NaN,Perpustakaan perguruan tinggi merupakan unsur ...,nan nan,Kesimpulan ini berdasarkan hasil analisa stati...
4,2541-3279-5,Edulibinfo,2541-3279,KONTRIBUSI LITERASI INFORMASI MAHASISWA TERHAD...,Septyanti Utami Solihat; Riche Cynthia Johan,2014,1,1,Universitas Pendidikan Indonesia; Universitas ...,Contribution; Information Literacy; Process of...,Fenomena pesatnya perkembangan ilmu pengetahua...,The phenomenon of the rapid development of sci...,Laporan ALA yang dijelaskan di atas dapat disi...,Pendekatan penelitian yang digunakan dalam pen...,NaN,NaN,1. Gambaran Umum Literasi Informasi Mahasiswa ...,Berdasarkan hasil penelitian “Kontribusi Lit e...

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7542 entries, 0 to 7541
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   7542 non-null   str
 1   Journal              7542 non-null   str
 2   ISSN                 7542 non-null   str
 3   Title                7542 non-null   str
 4   Authors              7536 non-null   str
 5   Year                 7542 non-null   int64
 6   Volume               7542 non-null   str
 7   Issue                7542 non-null   str
 8   Institution          7360 non-null   str
 9   Keywords             7273 non-null   str
 10  Abstrak              5890 non-null   str
 11  Abstract             6345 non-null   str
 12  Introduction         7542 non-null   str
 13  Method               5627 non-null   str
 14  Result               613 non-null    str
 15  Discussion           2112 non-null   str
 16  Result & Discussion  7542 non-null   str
 17  Conclusion           6699 non-null   str
dtypes: int64(1), str(17)
memory usage: 1.0 MB

In [48]:
df[['Title']].sample(20, random_state=42)

                                                  Title
3045                             BAHASA FORMAT CDS/ISIS
5484  Optimalisasi Pencapaian Visi dan Misi Melalui ...
1616  STRATEGI PELAYANAN PRIMA DI KANTOR PERPUSTAKAA...
6348  Komunikasi Lisan Dengan Tatap Muka Dalam Era T...
6357      Perpustakaan Perguruan Tinggi dan Plagiarisme
2759  IMPLEMENTASI STANDAR NASIONAL PERPUSTAKAAN (SN...
7213  Leaders of Public Service Organizations: Impro...
1872  PERSEPSI SISWA SMA NEGERI 1 PADANG TERHADAP PE...
2183  Kegiatan Pelestarian Bahan Pustaka Pasca Gempa...
5291  Literasi Pertanian dan Pengaruhnya Terhadap Pr...
7138  Kebijakan Pengembangan Koleksi E-Resources di ...
5457  Representasi Kepemimpinan Transformatif-Kolabo...
2943  Website sebagai Sarana Promosi Perpustakaan di...
332   IMPLEMENTASI KEBIJAKAN PENGEMBANGAN KOLEKSI DI...
5573       PERSONAL BRANDING PUSTAKAWAN DI PERPUSTAKAAN
7294  Literacy Strategy Information for Users of the...
1718  Pembuatan Direktori Perpustakaan Sekolah Selin...
2127  Pengaruh Desain Interior terhadap Produktivita...
4077  PERAN PENELITI BALAI PENELITIAN DAN PENGEMBANG...
7085  Peran Pemimpin dalam Menghadapi Trend Perpusta...

# Filter the dataset by removing rows with missing values in the Selected columns

In [49]:
# Filter the dataset by removing rows with missing values in the 'ID', 'Title' and 'Abstrak' columns
selected_columns = ['ID', 'Title', 'Abstrak']

df_filtered = df.dropna(subset=selected_columns)

df_filtered.info()

<class 'pandas.DataFrame'>
Index: 5890 entries, 0 to 7541
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   5890 non-null   str
 1   Journal              5890 non-null   str
 2   ISSN                 5890 non-null   str
 3   Title                5890 non-null   str
 4   Authors              5889 non-null   str
 5   Year                 5890 non-null   int64
 6   Volume               5890 non-null   str
 7   Issue                5890 non-null   str
 8   Institution          5814 non-null   str
 9   Keywords             5720 non-null   str
 10  Abstrak              5890 non-null   str
 11  Abstract             4763 non-null   str
 12  Introduction         5890 non-null   str
 13  Method               4557 non-null   str
 14  Result               502 non-null    str
 15  Discussion           1474 non-null   str
 16  Result & Discussion  5890 non-null   str
 17  Conclusion           5452 non-null   str
dtypes: int64(1), str(17)
memory usage: 874.3 KB

In [50]:
# Lowercase all the selected columns
df_filtered[selected_columns] = df_filtered[selected_columns].apply(lambda x: x.str.lower())

df_filtered[selected_columns].head()

,ID,Title,Abstrak
0,2541-3279-1,hubungan antara promosi perpustakaan melalui m...,penelitian ini dilatarbelakangi oleh perkemban...
1,2541-3279-2,hubungan antara penggunaan search features e-j...,penelitian ini membahas hubungan antara penggu...
2,2541-3279-3,hubungan antara ketersediaan fasilitas perpust...,penelitian ini membahas hubungan antara keters...
3,2541-3279-4,pengaruh kinerja terhadap layanan prima di cen...,masalah yang menjadi kajian dalam penelitian a...
4,2541-3279-5,kontribusi literasi informasi mahasiswa terhad...,fenomena pesatnya perkembangan ilmu pengetahua...

# Translate Title Column to Indonesian

In [51]:
df_selected = df_filtered[selected_columns]

df_selected.info()

<class 'pandas.DataFrame'>
Index: 5890 entries, 0 to 7541
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       5890 non-null   str
 1   Title    5890 non-null   str
 2   Abstrak  5890 non-null   str
dtypes: str(3)
memory usage: 184.1 KB

In [52]:
# Add column for translated content
# e.g. =GOOGLETRANSLATE(A1, "en", "id")

TRANSLATE_TEXT = "=GOOGLETRANSLATE({}, \"en\", \"id\")"

df_selected['title_translated'] = df_selected['Title'].apply(lambda x: TRANSLATE_TEXT.format(f'"{x}"'))
df_selected['abstrak_translated'] = df_selected['Abstrak'].apply(lambda x: TRANSLATE_TEXT.format(f'"{x}"'))
df_selected.head()

,ID,Title,Abstrak,title_translated,abstrak_translated
0,2541-3279-1,hubungan antara promosi perpustakaan melalui m...,penelitian ini dilatarbelakangi oleh perkemban...,"=GOOGLETRANSLATE(""hubungan antara promosi perp...","=GOOGLETRANSLATE(""penelitian ini dilatarbelaka..."
1,2541-3279-2,hubungan antara penggunaan search features e-j...,penelitian ini membahas hubungan antara penggu...,"=GOOGLETRANSLATE(""hubungan antara penggunaan s...","=GOOGLETRANSLATE(""penelitian ini membahas hubu..."
2,2541-3279-3,hubungan antara ketersediaan fasilitas perpust...,penelitian ini membahas hubungan antara keters...,"=GOOGLETRANSLATE(""hubungan antara ketersediaan...","=GOOGLETRANSLATE(""penelitian ini membahas hubu..."
3,2541-3279-4,pengaruh kinerja terhadap layanan prima di cen...,masalah yang menjadi kajian dalam penelitian a...,"=GOOGLETRANSLATE(""pengaruh kinerja terhadap la...","=GOOGLETRANSLATE(""masalah yang menjadi kajian ..."
4,2541-3279-5,kontribusi literasi informasi mahasiswa terhad...,fenomena pesatnya perkembangan ilmu pengetahua...,"=GOOGLETRANSLATE(""kontribusi literasi informas...","=GOOGLETRANSLATE(""fenomena pesatnya perkembang..."

In [54]:
OUTPUT_FOLDER = Path(DATA_FOLDER_FILE / 'translated')
OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)

df_selected.to_csv(OUTPUT_FOLDER / 'selected_data.csv', index=False)

print(f"Selected data saved to: {OUTPUT_FOLDER / 'selected_data.csv'}")

Selected data saved to: ..\..\data\translated\selected_data.csv