In [93]:
# Load Library

import numpy as np
import pandas as pd
from pathlib import Path
from lingua import Language, LanguageDetectorBuilder

DATA_FOLDER_FILE = Path('../../data/')
print(f"Data folder path: {DATA_FOLDER_FILE}")

Data folder path: ..\..\data

In [94]:
# Load the dataset
INPUT_PATH = Path(DATA_FOLDER_FILE / 'raw/main_data.csv')

df = pd.read_csv(INPUT_PATH, low_memory=False)
df.head()

,ID,Journal,ISSN,Title,Authors,Year,Volume,Issue,Institution,Keywords,Abstrak,Abstract,Introduction,Method,Result,Discussion,Result & Discussion,Conclusion
0,2541-3279-1,Edulibinfo,2541-3279,HUBUNGAN ANTARA PROMOSI PERPUSTAKAAN MELALUI M...,Dellia Pavillo Aribah; Rudi Susilana; Hada Hid...,2014,1,1,Universitas Pendidikan Indonesia; Universitas ...,Libraries; Library Promotion; Wall Magazine; V...,Penelitian ini dilatarbelakangi oleh perkemban...,This research is motivated by the development ...,Kehidupan adalah suatu proses yang dinamis dan...,Metode yang digunakan dalam penelitian ini ada...,NaN,NaN,Permasalahan yang ingin dijawab dalam peneliti...,Berdasarkan perolehan data dari penelititan pe...
1,2541-3279-2,Edulibinfo,2541-3279,HUBUNGAN ANTARA PENGGUNAAN SEARCH FEATURES e-J...,Hana Wandari; Dinn Wahyudin; Damayanty,2014,1,1,Universitas Pendidikan Indonesia; Universitas ...,Search Features e-Journals; information needs,Penelitian ini membahas hubungan antara penggu...,This research explain the relationship between...,Perpustakaan memiliki fungsi sebagai Sumber in...,Penelitian hubungan penggunaan search features...,NaN,NaN,Pembahasan hasil penelitian dilakukan untuk me...,Berdasarkan hasil penelitian yang telah dilaku...
2,2541-3279-3,Edulibinfo,2541-3279,HUBUNGAN ANTARA KETERSEDIAAN FASILITAS PERPUST...,Iis Aprianti; Rudi Susilana; Hada Hidayat Margana,2014,1,1,Universitas Pendidikan Indonesia; Universitas ...,Library facility; interests visit,Penelitian ini membahas hubungan antara keters...,This research explain the relationship between...,Perpustakaan merupakan sebuah institusi pengel...,Penelitian hubungan ketersediaan fasilitas per...,NaN,NaN,Pembahasan hasil penelitian dimaksudkan untuk ...,Hasil penelitian yang telah dilakukan menunjuk...
3,2541-3279-4,Edulibinfo,2541-3279,PENGARUH KINERJA TERHADAP LAYANAN PRIMA DI CEN...,Masitoh Hamdayani; Dinn Wahyudin; Euis Rosinar,2014,1,1,Universitas Pendidikan Indonesia; Universitas ...,Libraries; Library Promotion; Wall Magazine; V...,Masalah yang menjadi kajian dalam penelitian a...,This research is motivated by the development ...,Gudang buku dengan penataan dan pengelolaan as...,NaN,NaN,Perpustakaan perguruan tinggi merupakan unsur ...,nan nan,Kesimpulan ini berdasarkan hasil analisa stati...
4,2541-3279-5,Edulibinfo,2541-3279,KONTRIBUSI LITERASI INFORMASI MAHASISWA TERHAD...,Septyanti Utami Solihat; Riche Cynthia Johan,2014,1,1,Universitas Pendidikan Indonesia; Universitas ...,Contribution; Information Literacy; Process of...,Fenomena pesatnya perkembangan ilmu pengetahua...,The phenomenon of the rapid development of sci...,Laporan ALA yang dijelaskan di atas dapat disi...,Pendekatan penelitian yang digunakan dalam pen...,NaN,NaN,1. Gambaran Umum Literasi Informasi Mahasiswa ...,Berdasarkan hasil penelitian “Kontribusi Lit e...

In [95]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7542 entries, 0 to 7541
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   7542 non-null   str
 1   Journal              7542 non-null   str
 2   ISSN                 7542 non-null   str
 3   Title                7542 non-null   str
 4   Authors              7536 non-null   str
 5   Year                 7542 non-null   int64
 6   Volume               7542 non-null   str
 7   Issue                7542 non-null   str
 8   Institution          7360 non-null   str
 9   Keywords             7273 non-null   str
 10  Abstrak              5890 non-null   str
 11  Abstract             6345 non-null   str
 12  Introduction         7542 non-null   str
 13  Method               5627 non-null   str
 14  Result               613 non-null    str
 15  Discussion           2112 non-null   str
 16  Result & Discussion  7542 non-null   str
 17  Conclusion           6699 non-null   str
dtypes: int64(1), str(17)
memory usage: 1.0 MB

In [96]:
df[['Title']].sample(20, random_state=42)

                                                  Title
3045                             BAHASA FORMAT CDS/ISIS
5484  Optimalisasi Pencapaian Visi dan Misi Melalui ...
1616  STRATEGI PELAYANAN PRIMA DI KANTOR PERPUSTAKAA...
6348  Komunikasi Lisan Dengan Tatap Muka Dalam Era T...
6357      Perpustakaan Perguruan Tinggi dan Plagiarisme
2759  IMPLEMENTASI STANDAR NASIONAL PERPUSTAKAAN (SN...
7213  Leaders of Public Service Organizations: Impro...
1872  PERSEPSI SISWA SMA NEGERI 1 PADANG TERHADAP PE...
2183  Kegiatan Pelestarian Bahan Pustaka Pasca Gempa...
5291  Literasi Pertanian dan Pengaruhnya Terhadap Pr...
7138  Kebijakan Pengembangan Koleksi E-Resources di ...
5457  Representasi Kepemimpinan Transformatif-Kolabo...
2943  Website sebagai Sarana Promosi Perpustakaan di...
332   IMPLEMENTASI KEBIJAKAN PENGEMBANGAN KOLEKSI DI...
5573       PERSONAL BRANDING PUSTAKAWAN DI PERPUSTAKAAN
7294  Literacy Strategy Information for Users of the...
1718  Pembuatan Direktori Perpustakaan Sekolah Selin...
2127  Pengaruh Desain Interior terhadap Produktivita...
4077  PERAN PENELITI BALAI PENELITIAN DAN PENGEMBANG...
7085  Peran Pemimpin dalam Menghadapi Trend Perpusta...

# Filter the dataset by removing rows with missing values in the Selected columns

In [97]:
# Filter the dataset by removing rows with missing values in the 'ID', 'Title' and 'Abstrak' columns
selected_columns = ['ID', 'Title', 'Abstrak']

df_filtered = df.dropna(subset=selected_columns)

df_filtered.info()

<class 'pandas.DataFrame'>
Index: 5890 entries, 0 to 7541
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   5890 non-null   str
 1   Journal              5890 non-null   str
 2   ISSN                 5890 non-null   str
 3   Title                5890 non-null   str
 4   Authors              5889 non-null   str
 5   Year                 5890 non-null   int64
 6   Volume               5890 non-null   str
 7   Issue                5890 non-null   str
 8   Institution          5814 non-null   str
 9   Keywords             5720 non-null   str
 10  Abstrak              5890 non-null   str
 11  Abstract             4763 non-null   str
 12  Introduction         5890 non-null   str
 13  Method               4557 non-null   str
 14  Result               502 non-null    str
 15  Discussion           1474 non-null   str
 16  Result & Discussion  5890 non-null   str
 17  Conclusion           5452 non-null   str
dtypes: int64(1), str(17)
memory usage: 874.3 KB

In [98]:
# Lowercase all the selected columns
df_filtered[selected_columns] = df_filtered[selected_columns].apply(lambda x: x.str.lower())

df_filtered[selected_columns].head()

,ID,Title,Abstrak
0,2541-3279-1,hubungan antara promosi perpustakaan melalui m...,penelitian ini dilatarbelakangi oleh perkemban...
1,2541-3279-2,hubungan antara penggunaan search features e-j...,penelitian ini membahas hubungan antara penggu...
2,2541-3279-3,hubungan antara ketersediaan fasilitas perpust...,penelitian ini membahas hubungan antara keters...
3,2541-3279-4,pengaruh kinerja terhadap layanan prima di cen...,masalah yang menjadi kajian dalam penelitian a...
4,2541-3279-5,kontribusi literasi informasi mahasiswa terhad...,fenomena pesatnya perkembangan ilmu pengetahua...

# Detect Language of the Title Columns

In [99]:
df_selected = df_filtered[selected_columns]

df_selected.info()

<class 'pandas.DataFrame'>
Index: 5890 entries, 0 to 7541
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       5890 non-null   str
 1   Title    5890 non-null   str
 2   Abstrak  5890 non-null   str
dtypes: str(3)
memory usage: 184.1 KB

In [100]:
detector = LanguageDetectorBuilder.from_languages(
    Language.INDONESIAN,
    Language.ENGLISH
).build()

def detect_language(text):
    if pd.isna(text) or not str(text).strip():
        return pd.Series({
            "language": "missing",
            "confidence": np.nan,
        })

    text = str(text).strip()
    try:
        confidence_values = detector.compute_language_confidence_values(text)
        detected = detector.detect_language_of(text)

        if detected is None or len(confidence_values) == 0:
            return pd.Series({
                "language": "uncertain",
                "confidence": np.nan,
            })

        language = detected.iso_code_639_1.name.lower()
        top_confidence = float(confidence_values[0].value)

        return pd.Series({
            "language": language,
            "confidence": top_confidence,
        })
    except Exception as exc:
        return pd.Series({
            "language": "uncertain",
            "confidence": np.nan,
        })

In [102]:
# Deteksi judul dan abstrak secara terpisah; teks asli dipertahankan
title_lang = df_selected["Title"].apply(detect_language).add_prefix("title_")
abstract_lang = df_selected["Abstrak"].apply(detect_language).add_prefix("abstract_")

df_audit = pd.concat([df_selected, title_lang, abstract_lang], axis=1)

display(df_audit[[
    "ID", "Title", "Abstrak",
    "title_language", "title_confidence",
    "abstract_language", "abstract_confidence",
]].sample(min(20, len(df_audit)), random_state=42))

,ID,Title,Abstrak,title_language,title_confidence,abstract_language,abstract_confidence
6088,2654-6469-74,analisis kontribusi perpustakaan indonesian vi...,penelitian ini bertujuan untuk mengetahui kont...,id,0.999872,id,1.0
1145,1410-5551-104,tingkat kepuasan pemustaka terhadap mutu pelay...,penelitian ini bertujuan untuk mengetahui seja...,id,1.000000,id,1.0
1164,1410-5551-123,keaktifan pustakawan dalam pemasyarakatan perp...,tulisan ini bertujuan untuk memaparkan keaktif...,id,1.000000,id,1.0
4645,2775-8761-38,dampak rendahnya perpustakaan di masa pandemi ...,masalah yang dihadapi sekolah saat ini adalah ...,id,0.999953,id,1.0
5724,2502-4108-218,representasi profesionalisme pustakawan dalam ...,film memiliki peranan penting dalam membentuk ...,id,0.819430,id,1.0
2705,2598-7852-20,persepsi pemustaka terhadap penerapan peminjam...,penelitian ini bertujuan untuk mengetahui baga...,id,1.000000,id,1.0
995,2723-0953-21,pengaruh gerakan literasi sekolah terhadap pen...,penelitian ini bertujuan untuk mengetahui peng...,id,1.000000,id,1.0
5982,2579-3160-77,prinsip etika dan tata kelola pengembangan tek...,keberhasilan tata ti dalam organisasi sangat k...,id,0.999993,id,1.0
1175,1410-5551-134,membisniskan layanan perpustakaan menggunakan ...,perpustakaan sebagai pusat informasi tidak saj...,id,0.999982,id,1.0
5038,2442-7799-62,peran tenaga perpustakaan dalam mewujudkan keb...,penelitian ini berupaya untuk mengetahui peran...,id,1.000000,id,1.0
2589,2549-1334-150,trends in library science research topics duri...,"sejak berdiri tahun 1999 lalu, telah ada ratus...",en,0.998590,id,1.0
6429,2580-3662-146,metode analisis wacana teun van djik dalam pen...,adopsi dari teknologi informasi pada ilmu perp...,id,0.999973,id,1.0
6023,2654-6469-9,kompetensi brainware dalam eksistensi sistem i...,kompetensi merupakan kemampuan untuk melakukan...,id,1.000000,id,1.0
2313,2540-9239-131,praktik signifikasi atas transformasi pelayana...,transformasi pelayanan referensi perpustakaan ...,id,0.999995,id,1.0
356,2798-9607-14,print mass media strategies in central java an...,kemunculan internet yang memliki kekuatan konv...,en,0.958361,id,1.0
6296,2580-3662-13,vandalisme koleksi di unit pelayanan teknis (u...,vandalisme mengakibatkan hilangnya keindahan b...,id,0.999975,id,1.0
2107,2597-9957-22,model evaluasi kinerja pustakawan sebagai dasa...,penelitian bertujuan untuk (1) mengevaluasi ko...,id,0.999992,id,1.0
2483,2549-1334-44,representasi tingkat kepuasan pemustaka terhad...,perpustakaan perguruan tinggi sebagai salah sa...,id,1.000000,id,1.0
863,2657-2346-6,preservasi naskah budaya di museum sonobudoyo,manuskrip adalah salah satu kekayaan bangsa di...,id,0.995889,id,1.0
564,2598-3040-60,proses pelaksanaan biblioterapi sebagai altern...,"berdasarkan hasil penelitian, tantangan litera...",id,0.999993,id,1.0

# Translate Title Column to Indonesian

In [ ]:
# # Add column for translated content
# e.g. =GOOGLETRANSLATE(A1, "en", "id")
TRANSLATE_TEXT = "=GOOGLETRANSLATE({}; \"en\"; \"id\")"

# Only translate titles that have _language = "en"
# if title_language is not "en", then leave it as is (no translation needed), copy the original title to the new column
title_english_mask = title_lang["title_language"].eq("en")
abstract_english_mask = abstract_lang["abstract_language"].eq("en")

df_selected["title_translated"] = pd.Series(index=df_selected.index, dtype="object")
df_selected.loc[title_english_mask, "title_translated"] = df_selected.loc[title_english_mask, "Title"].astype(str).apply(
    lambda x: TRANSLATE_TEXT.format(f'"{x}"')
)

df_selected["abstract_translated"] = pd.Series(index=df_selected.index, dtype="object")
df_selected.loc[abstract_english_mask, "abstract_translated"] = df_selected.loc[abstract_english_mask, "Abstrak"].astype(str).apply(
    lambda x: TRANSLATE_TEXT.format(f'"{x}"')
)

df_selected.head()

,ID,Title,Abstrak,title_translated,abstract_translated
0,2541-3279-1,hubungan antara promosi perpustakaan melalui m...,penelitian ini dilatarbelakangi oleh perkemban...,hubungan antara promosi perpustakaan melalui m...,penelitian ini dilatarbelakangi oleh perkemban...
1,2541-3279-2,hubungan antara penggunaan search features e-j...,penelitian ini membahas hubungan antara penggu...,hubungan antara penggunaan search features e-j...,penelitian ini membahas hubungan antara penggu...
2,2541-3279-3,hubungan antara ketersediaan fasilitas perpust...,penelitian ini membahas hubungan antara keters...,hubungan antara ketersediaan fasilitas perpust...,penelitian ini membahas hubungan antara keters...
3,2541-3279-4,pengaruh kinerja terhadap layanan prima di cen...,masalah yang menjadi kajian dalam penelitian a...,pengaruh kinerja terhadap layanan prima di cen...,masalah yang menjadi kajian dalam penelitian a...
4,2541-3279-5,kontribusi literasi informasi mahasiswa terhad...,fenomena pesatnya perkembangan ilmu pengetahua...,kontribusi literasi informasi mahasiswa terhad...,fenomena pesatnya perkembangan ilmu pengetahua...

In [109]:
OUTPUT_FOLDER = Path(DATA_FOLDER_FILE / 'translated')
OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)

df_selected.to_csv(OUTPUT_FOLDER / 'selected_data.csv', index=False)

print(f"Selected data saved to: {OUTPUT_FOLDER / 'selected_data.csv'}")

Selected data saved to: ..\..\data\translated\selected_data.csv