In [1]:
from pathlib import Path
import re
import unicodedata

import joblib
import nltk
import numpy as np
import pandas as pd
from IPython.display import display
from nltk.corpus import stopwords
from scipy.sparse import load_npz
from sklearn.metrics.pairwise import cosine_similarity
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

nltk.download("stopwords", quiet=True)

DATA_FOLDER = Path("../../data")
FEATURE_FOLDER = DATA_FOLDER / "features" / "tfidf"

MATRIX_PATH = FEATURE_FOLDER / "tfidf_matrix.npz"
VECTORIZER_PATH = FEATURE_FOLDER / "tfidf_vectorizer.joblib"

DOCUMENTS_PATH = FEATURE_FOLDER / "tfidf_documents.csv"

print(f"Feature folder: {FEATURE_FOLDER.resolve()}")

Feature folder: C:\Works\uts-ir\src\data\features\tfidf

In [2]:
X_main = load_npz(MATRIX_PATH)
vectorizer = joblib.load(VECTORIZER_PATH)
df = pd.read_csv(DOCUMENTS_PATH, low_memory=False)

df.head()

,id,title,abstract,title_translated,abstract_translated,processed_token_text,processed_text
0,2541-3279-1,hubungan antara promosi perpustakaan melalui m...,penelitian ini dilatarbelakangi oleh perkemban...,hubungan antara promosi perpustakaan melalui m...,penelitian ini dilatarbelakangi oleh perkemban...,"['hubung', 'promosi', 'pustaka', 'majalah', 'd...",hubung promosi pustaka majalah dinding minat k...
1,2541-3279-2,hubungan antara penggunaan search features e-j...,penelitian ini membahas hubungan antara penggu...,hubungan antara penggunaan search features e-j...,penelitian ini membahas hubungan antara penggu...,"['hubung', 'guna', 'search', 'features', 'jour...",hubung guna search features journals penuh but...
2,2541-3279-3,hubungan antara ketersediaan fasilitas perpust...,penelitian ini membahas hubungan antara keters...,hubungan antara ketersediaan fasilitas perpust...,penelitian ini membahas hubungan antara keters...,"['hubung', 'sedia', 'fasilitas', 'pustaka', 'm...",hubung sedia fasilitas pustaka minat kunjung s...
3,2541-3279-4,pengaruh kinerja terhadap layanan prima di cen...,masalah yang menjadi kajian dalam penelitian a...,pengaruh kinerja terhadap layanan prima di cen...,masalah yang menjadi kajian dalam penelitian a...,"['pengaruh', 'kerja', 'layan', 'prima', 'cente...",pengaruh kerja layan prima center of informati...
4,2541-3279-5,kontribusi literasi informasi mahasiswa terhad...,fenomena pesatnya perkembangan ilmu pengetahua...,kontribusi literasi informasi mahasiswa terhad...,fenomena pesatnya perkembangan ilmu pengetahua...,"['kontribusi', 'literasi', 'informasi', 'mahas...",kontribusi literasi informasi mahasiswa proses...

In [3]:
def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text)
    text = unicodedata.normalize("NFC", text)
    text = text.casefold()
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b", " ", text)
    text = re.sub(r"\d+", " ", text)
    text = re.sub(r"[^\w\s]", " ", text, flags=re.UNICODE)
    text = text.replace("_", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text

stopwords_id = set(stopwords.words("indonesian"))
stemmer = StemmerFactory().create_stemmer()

def preprocess_query(query):
    normalized_query = normalize_text(query)
    tokens = normalized_query.split()
    tokens_no_stopwords = [
        token for token in tokens
        if token not in stopwords_id and len(token) > 1
    ]
    tokens_stemmed = [stemmer.stem(token) for token in tokens_no_stopwords]
    processed_query = " ".join(tokens_stemmed)

    return {
        "normalized_query": normalized_query,
        "tokens": tokens,
        "tokens_no_stopwords": tokens_no_stopwords,
        "tokens_stemmed": tokens_stemmed,
        "processed_query": processed_query,
    }

In [4]:
def search_articles(query, top_k=10):
    if not isinstance(query, str) or not query.strip():
        raise ValueError("Query tidak boleh kosong. Masukkan kata atau frasa pencarian.")
    if not isinstance(top_k, int) or top_k < 1:
        raise ValueError("top_k harus berupa bilangan bulat positif.")

    query_steps = preprocess_query(query)
    processed_query = query_steps["processed_query"]

    if not processed_query:
        print("Query menjadi kosong setelah preprocessing. Coba gunakan istilah yang lebih spesifik.")
        return pd.DataFrame()

    query_vector = vectorizer.transform([processed_query])
    query_terms = processed_query.split()
    out_of_vocabulary = [term for term in query_terms if term not in vectorizer.vocabulary_]

    if query_vector.nnz == 0:
        print("Tidak ada term query yang ditemukan dalam vocabulary TF-IDF.")
        if out_of_vocabulary:
            print("Term di luar vocabulary:", ", ".join(dict.fromkeys(out_of_vocabulary)))
        return pd.DataFrame()

    scores = cosine_similarity(query_vector, X_main).ravel()
    ranked_indices = np.argsort(scores)[::-1]
    ranked_indices = [idx for idx in ranked_indices if scores[idx] > 0][:top_k]

    if not ranked_indices:
        print("Tidak ditemukan dokumen dengan skor cosine similarity di atas nol.")
        return pd.DataFrame()

    columns_available = set(df.columns)
    display_columns = [
        column for column in ["id", "title", "abstract"]
        if column in columns_available
    ]
    results = df.iloc[ranked_indices][display_columns].copy()
    results.insert(0, "rank", np.arange(1, len(results) + 1))
    results["cosine_similarity"] = scores[ranked_indices]
    results = results.sort_values("cosine_similarity", ascending=False).reset_index(drop=True)

    print(f"Query            : {query}")
    print(f"Processed Query  : {processed_query}")
    print(f"Term ditemukan   : {query_vector.nnz} term(s) dalam vocabulary.")
    if out_of_vocabulary:
        print("Term di luar vocabulary:", ", ".join(dict.fromkeys(out_of_vocabulary)))

    return results

In [5]:
query = "bagaimana cara meningkatkan literasi informasi mahasiswa?"
results = search_articles(query, top_k=10)

# Show all results without truncation
display(results)

Query            : bagaimana cara meningkatkan literasi informasi mahasiswa?
Processed Query  : tingkat literasi informasi mahasiswa
Term ditemukan   : 4 term(s) dalam vocabulary.

,rank,id,title,abstract,cosine_similarity
0,1,2797-9393-24,peran pustakawan referensi perpustakaan uin im...,perpustakaan perguruan tinggi memiliki peran p...,0.629416
1,2,2657-2346-104,ngkat literasi informasi dan literasi akademik...,mahasiswa memiliki peran tidak hanya sebagai p...,0.577379
2,3,2598-7852-71,urgensi kelas literasi informasi bagi mahasisw...,artikel ini bertujuan untuk mengetahui urgensi...,0.558507
3,4,2685-8363-25,strategi peningkatan kompetensi literasi infor...,artikel ini membahas mengenai strategi meningk...,0.553064
4,5,2723-7605-40,kemampuan literasi informasi mahasiswa prodi m...,penelitian ini bertujuan menganalisis kemampua...,0.530804
5,6,2829-9531-18,evaluasi tingkat literasi informasi mahasiswa ...,penelitian ini bertujuan untuk mengidentifikas...,0.526409
6,7,2541-3279-5,kontribusi literasi informasi mahasiswa terhad...,fenomena pesatnya perkembangan ilmu pengetahua...,0.520446
7,8,2715-274x-161,optimalisasi peran perpustakaan dalam meningka...,penelitian ini bertujuan untuk mengeksplorasi ...,0.519991
8,9,2540-9239-182,identifying information literacy skills of new...,perpustakaan sekolah pascasarjana uin syarif h...,0.517218
9,10,2723-7605-39,peran intervensi pustakawan dalam meningkatkan...,peningkatan literasi informasi menjadi sebuah ...,0.514313

In [ ]:
test_queries = [
    "bagaimana cara meningkatkan literasi informasi mahasiswa?",
    "sangkut paut game dalam pendidikan",
    "dampak pandemi covid-19 terhadap pendidikan",
]

# No Truncation of columns in the output display()
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

for test_query in test_queries:
    test_results = search_articles(test_query, top_k=10)
    display(test_results[[
        column for column in ["rank", "id", "title", "abstract", "cosine_similarity"]
        if column in test_results.columns
    ]])

Query            : bagaimana cara meningkatkan literasi informasi mahasiswa?
Processed Query  : tingkat literasi informasi mahasiswa
Term ditemukan   : 4 term(s) dalam vocabulary.

,rank,id,title,abstract,cosine_similarity
0,1,2797-9393-24,peran pustakawan referensi perpustakaan uin imam bonjol padang dalam meningkatkan literasi informasi mahasiswa,"perpustakaan perguruan tinggi memiliki peran penting dalam mendukung proses pengajaran dan penelitian serta memenuhi kebutuhan informasi sivitas akademika terutama mahasiswa. peningkatan literasi informasi mahasiswa sangat diperlukan guna membantu penelusuran dan penggunaan informasi yang efektif dan efisien. kemampuan mahasiswa terkait literasi informasi akan mempermudah dalam membuat karya tulis ilmiah dan pengerjaan tugas kuliah. pustakawan referensi memiliki peran membantu pengguna untuk menemukan informasi yang dibutuhkan secara efektif dan efisien. tujuan penelitian ini untuk dapat mengetahui sejauh mana peran pustakawan referensi dalam peningkatan literasi informasi bagi mahasiswa. metode yang digunakan dalam penulisan artikel ini yaitu metode penelitian deskriptif melalui pendekatan kualitatif. teknik pengumpulan data melalui wawancara, observasi dan studi literatur. penelitian ini menunjukkan pustakawan referensi telah melakukan perannnya dalam meningkatkan literasi informasi, seperti pelatihan dan paket literasi informasi serta berbagai layanan guna meningkatkan kemampuan literasi informasi mahasiswa uin imam bonjol padang.",0.629416
1,2,2657-2346-104,ngkat literasi informasi dan literasi akademik pada mahasiswa uin fatmawati sukarno bengkulu tahun ajaran 2022/2023,"mahasiswa memiliki peran tidak hanya sebagai pembelajar namun juga sebagai penggerak perubahan dan kontrol sosial dalam masyarakat. peran ini menuntut mahasiswa untuk menguasai berbagai kemampuan, termasuk literasi informasi dan literasi ilmiah. kajian terdahulu mengindikasikan adanya kebutuhan mendesak untuk menggali lebih dalam mengenai literasi informasi dan ilmiah di kalangan mahasiswa. penelitian ini bertujuan untuk memberikan gambaran mendalam mengenai tingkat literasi informasi dan ilmiah di kalangan mahasiswa uin fatmawati sukarno bengkulu. desain penelitian ini adalah mix-method dengan menggabungkan data dari kuesioner, focus group discussion, dan tes essay. responden penelitian ini terdiri dari berbagai tingkatan semester dengan total responden berjumlah 80 mahasiswa. hasil penelitian menunjukkan pemahaman literasi informasi dan literasi ilmiah mahasiswa perlu lebih ditingkatkan terutama dalam hal pengaplikasian pengetahuan dalam kegiatan menulis ilmiah.",0.577379
2,3,2598-7852-71,urgensi kelas literasi informasi bagi mahasiswa di perpustakaan universitas muhammadiyah gombong,"artikel ini bertujuan untuk mengetahui urgensi kelas literasi informasi bagi mahasiswa di perpustakaan universitas muhammadiyah gombong. perkembangan teknologi informasi saat ini bukan lagi mengalami evolusi, tetapi sudah menjadi sebuah revolusi informasi yang sangat dahsyat. untuk itu dibutuhkan kemampuan untuk memfilter dari semua informasi yang ada,. perpustakaan sebagai penyedia dan pengelola sekaligus sebagai wahana informasi, maka pustakawan berperan penting dalam memberikan bimbingan penelusuran informasi yang dibutuhkan pemustaka atau mahasiswa. metode penelitian yang digunakan dalam artikel ini yaitu dengan metode deskriptif kualitatif dengan mengkaji secara mendalam terhadap suatu permasalahan. teknik pengumpulan datanya dengan wawancara dan studi literatur. wawancara dilakukan dengan responden mahasiswa, dosen dan pustakawan. dari hasil penelitian dapat disimpulkan bahwa mahasiswa membutuhkan pendampingan dan bimbingan dalam melakukan literasi informasi, sehingga perlu diadakan atau diselenggarakan kelas literasi informasi, hal itu sebagai upaya perpustakaan dalam memberikan layanan literasi informasi. perpustakaan bekerja sama dengan program studi mewajibkan mahasiswa mengikuti kuliah literasi informasi di kelas. dalam kegiatan literasi informasi ini tema yang disampaikan menyesuaikan dengan kebutuhan mahasiswa ,adapun tema- tema literasi yang telah dijalankan antara lain:1} penelusuran ejournal 2) manajemen referensi mendeley, 3)plagiarisme, 4) media presentasi online.",0.558507
3,4,2685-8363-25,strategi peningkatan kompetensi literasi informasi mahasiswa dalam mendukung tri dharma perguruan tinggi,"artikel ini membahas mengenai strategi meningkatkan kompetensi literasi informasi bagi mahasiswa dan menjelaskan manfaatnya. strategi yang dibutuhkan agar mahasiswa memiliki kompetensi literasi informasi berbasis teknologi informasi, yaitu: mengasah diri mengikuti kegiatan pendidikan pemustaka, aktif mengikuti pelatihan literasi informasi, wajib memiliki kemampuan literasi digital, piawai menelusur melalui sumber informasi elektronik, menguasai teknik penelusuran informasi menggunakan mesin pencari, rajin mengikuti pelatihan manajemen dokumen ilmiah, serta memahami etika penggunaan informasi. manfaat yang diperoleh mahasiswa yang selalu meningkatkan kompetensi literasi informasi, seperti memudahkan dalam hal strategi mencari informasi, untuk akses informasi elektronik, mengelola sumber referensi yang dimiliki, dan dalam pembuatan karya tulis ilmiah.",0.553064
4,5,2723-7605-40,kemampuan literasi informasi mahasiswa prodi manajemen pendidikan islam angkatan 2019 universitas islam negeri maulana malik ibrahim malang dalam menyelesaikan tugas akhir menggunakan model the seven pillar,"penelitian ini bertujuan menganalisis kemampuan literasi informasi mahasiswa prodi manajemen pendidikan islam angkatan 2019 dalam menyelesaikan tugas akhir menggunakan model the seven pillars sebagai dasar untuk meningkatkan pemahaman dan keterampilan literasi informasi mahasiswa dalam mengakses, mengevaluasi, menggunakan, dan berbagi informasi secara efektif. pendekatan dengan penekanan pada kualitatif yang digunakan dalam penelitian ini dengan melibatkan lima mahasiswa yang sedang menjalani tugas akhir. mahasiswa jurusan manajemen pendidikan islam angkatan 2019 memiliki pemahaman yang komprehensif tentang literasi informasi dan menyadari pentingnya kemampuan ini. mereka menggunakan sumber informasi tercetak seperti buku dan sumber informasi online seperti jurnal sesuai dengan kebutuhan mereka. namun, ditemukan bahwa mahasiswa mengalami kesulitan dalam memilih dan menemukan informasi yang relevan di tengah luasnya informasi yang tersedia di internet. mahasiswa jurusan manajemen pendidikan islam angkatan 2019 memiliki pemahaman yang komprehensif tentang literasi informasi dan menggunakan sumber-sumber informasi dengan efektif. mereka perlu meningkatkan penggunaan alat temu kembali informasi dan keterampilan dalam mengevaluasi informasi. penting bagi universitas untuk meningkatkan pelatihan literasi informasi bagi mahasiswa, khususnya dalam penggunaan alat temu kembali informasi. mahasiswa perlu diberikan panduan dalam mengevaluasi dan memilih informasi yang akurat.",0.530804
5,6,2829-9531-18,evaluasi tingkat literasi informasi mahasiswa jurusan ilmu perpustakaan dalam penyelesaian skripsi di fakultas adab dan humaniora: studi kasus model-model literasi informasi,"penelitian ini bertujuan untuk mengidentifikasi dan mengevaluasi modelmodel literasi informasi yang digunakan oleh mahasiswa jurusan ilmu perpustakaan dalam menghadapi tugas akhir (skripsi). metodologi penelitian yang digunakan adalah jenis penelitian deskriptif dengan pendekatan kualitatif. data primer dikumpulkan melalui wawancara dengan mahasiswa angkatan 2019 yang sedang mengerjakan skripsi, sedangkan data sekunder diperoleh dari referensi yang relevan dengan penelitian ini. hasil penelitian ini mengungkapkan beragam model literasi informasi yang digunakan oleh mahasiswa dalam pencarian informasi yang dibutuhkan untuk menyelesaikan tugas akhir. namun, temuan utama adalah bahwa mahasiswa dalam jurusan ilmu perpustakaan tidak selalu mengikuti tahapan panduan yang terdapat di dalam model-model literasi informasi. sebaliknya, mereka melakukan berbagai keterampilan seperti menentukan topik, mencari referensi, merumuskan masalah, menyeleksi informasi, mengorganisasi data, dan menciptakan konten skripsi secara fleksibel sesuai dengan kebutuhan dan konteks penelitian mereka. penelitian ini memberikan wawasan yang berharga tentang praktik literasi informasi mahasiswa jurusan ilmu perpustakaan dan dapat digunakan sebagai dasar untuk pengembangan program literasi informasi yang lebih efektif di masa mendatang. hasil penelitian ini juga memperkuat pentingnya pendekatan fleksibel terhadap literasi informasi yang memungkinkan mahasiswa untuk mengembangkan keterampilan yang sesuai dengan kebutuhan mereka.",0.526409
6,7,2541-3279-5,kontribusi literasi informasi mahasiswa terhadap proses penulisan karya ilmiah,"fenomena pesatnya perkembangan ilmu pengetahuan dan teknologi informasi pada era globalisasi membuat meledaknya informasi yang tersedia dalam berbagai macam format dan sumber. ledakan informasi memudahkan manusia khususnya mahasiswa dalam mengakses dan memperoleh informasi namun membuat mereka kesulitan dalam memilih informasi yang relevan dengan kebutuhannya. mahasiswa memerlukan kemampuan dalam mengelola informasi untuk dapat mempermudah mereka dalam8 mengerjakan tugas akademisnya terutama tugas akhirnya. penelitian ini merupakan penelitian kuantitatif yang bertujuan untuk mengetahui: 1) gambaran kondisi literasi informasi mahasiswa; 2) gambaran proses penulisan karya ilmiah yang dilakukan oleh mahasiswa; dan 3) kontribusi literasi informasi mahasiswa terhadap proses penulisan karya ilmiah. metode penelitian yang digunakan adalah metode deskriptif dengan pendekatan kuantitatif. populasi dalam penelitian ini adalah mahasiswa universitas pendidikan indonesia angkatan 2010 di tiga fakultas, dengan sampel sebanyak 87 orang yang dihitung berdasarkan rumus slovin dengan metode proportionate stratified random sampling. teknik pengumpulan data menggunakan angket tertutup dengan skala likert dengan analisis data menggunakan analisis deskriptif dan korelasi. untuk mengetahui kontribusi literasi informasi terhadap proses penulisan karya ilmiah digunakan rumus pearson product moment. berdasarkan hasil analisis data dapat diketahui bahwa: 1) literasi informasi mahasiswa memberikan kontribusi sebesar 31,06% terhadap proses penulisan karya ilmiah; 2) secara garis besar kondisi literasi informasi mahasiswa tergolong kedalam kategori baik; dan 3) proses penulisan karya ilmiah yang dilakukan oleh mahasiswa termasuk kedalam kategori baik. dengan demikian dapat disimpulkan bahwa literasi informasi mahasiswa berkontribusi sedang terhadap proses penulisan karya ilmiah.",0.520446
7,8,2715-274x-161,optimalisasi peran perpustakaan dalam meningkatkan literasi media mahasiswa,"penelitian ini bertujuan untuk mengeksplorasi peran perpustakaan dalam meningkatkan literasi media mahasiswa di universitas negeri malang melalui pendekatan deskriptif kualitatif. dalam upaya memahami dinamika ini, kami mengumpulkan data melalui observasi langsung dan wawancara mendalam dengan mahasiswa serta staf perpustakaan. hasil penelitian menunjukkan bahwa meskipun perpustakaan telah menyediakan berbagai program literasi media dan sumber daya yang relevan, efektivitasnya masih terbatas oleh beberapa faktor, termasuk kurangnya partisipasi mahasiswa dan rendahnya integrasi program literasi media ke dalam kurikulum akademik. lebih lanjut, ditemukan bahwa sebagian besar mahasiswa belum memiliki kemampuan yang memadai untuk menganalisis dan mengevaluasi informasi secara kritis, yang disebabkan oleh kurangnya sosialisasi program serta metode pembelajaran yang masih bersifat teoretis tanpa aplikasi praktis yang memadai. berdasarkan temuan tersebut, penelitian ini menyarankan perlunya peningkatan strategi sosialisasi, pengembangan program literasi media yang lebih interaktif dan berbasis pada kebutuhan mahasiswa, serta kolaborasi yang lebih erat antara perpustakaan dan fakultas untuk memastikan literasi media menjadi bagian integral dari pendidikan tinggi",0.519991
8,9,2540-9239-182,identifying information literacy skills of new graduate students,"perpustakaan sekolah pascasarjana uin syarif hidayatullah jakarta menyelenggarakan program literasi informasi untuk menciptakan mahasiswa baru yang mahir ketika dihadapkan dengan tugas-tugas akademik. memahami keterampilan awal literasi informasi mahasiswa menjadi penting diperhatikan karena merupakan input untuk pengembangan program literasi informasi yang lebih berorientasi kebutuhan mahasiswa. penelitian ini bertujuan untuk mengidentifikasi keterampilan awal literasi informasi mahasiswa baru pascasarjana berbasis model big6. pendekatan penelitian adalah kuantitatif dengan metode survei. sampel berjumlah 43 responden diambil dari total populasi 160 menggunakan teknik insidental, yaitu menjadikan mahasiswa yang hadir secara langsung ketika orientasi mahasiswa baru semester ganjil 2022. pengumpulan data melalui kuesioner tertutup dengan skala likert. analisis dan interpretasi data menggunakan statistik deskriptif. hasil penelitian menunjukkan keterampilan literasi informasi mahasiswa baru adalah 70%, berkategori baik. mahasiswa terkonfirmasi melakukan evaluasi hasil penelusuran sebesar 74% sedangkan seeking strategies dan the use of information, yaitu 68% dan 69, (kategori cukup). kondisi keterampilan task definition dan synthesis sebesar 71%, location and access 70% dengan google scholar, academia, dan moraref sebagai sumber informasi digital paling banyak direferensikan, ketiga aspek dikategorikan baik. mayoritas mahasiswa sudah memanfaatkan aplikasi manajemen referensi, meliputi menu referensi bawaan office word processor, footnote, mendeley dan zotero. keterampilan awal literasi informasi mahasiswa baru sekolah pascasarjana secara keseluruhan berkategori baik. mahasiswa memiliki keunggulan dalam mendefinisikan kebutuhan, menentukan lokasi sumber informasi dan mensintesis. penyusunan strategi penelusuran dan menggunakan sumber informasi berkategori cukup, sehingga menjadi fokus pelatihan literasi informasi di masa mendatang.",0.517218
9,10,2723-7605-39,peran intervensi pustakawan dalam meningkatkan literasi informasi: studi kualitatif dalam lingkungan akademik di universitas jenderal achmad yani yogyakarta,"peningkatan literasi informasi menjadi sebuah keharusan di era digital ini, di mana akses terhadap berbagai sumber informasi semakin mudah namun juga kompleks. di lingkungan akademik, mahasiswa dihadapkan pada tuntutan untuk memiliki keterampilan literasi informasi yang baik agar dapat mengakses, mengevaluasi, dan menggunakan informasi dengan cerdas. dalam konteks ini, peran pustakawan tidak hanya sebatas sebagai penyedia sumber informasi, tetapi juga sebagai fasilitator utama dalam mengembangkan literasi informasi mahasiswa. adapun rumusan masalah dalam penelitian ini adalah sejauh mana intervensi pustakawan dapat meningkatkan literasi informasi mahasiswa di lingkungan akademik universitas jenderal achmad yani yogyakarta. penelitian ini bertujuan untuk mengeksplorasi dan menganalisis upaya meningkatkan literasi informasi di lingkungan akademik universitas jenderal achmad yani yogyakarta melalui pendekatan kualitatif. penelitian ini melibatkan intervensi pustakawan dengan fokus pada pengembangan keterampilan literasi informasi mahasiswa. metode penelitian kualitatif digunakan untuk menggali pengalaman, persepsi, dan dampak intervensi pustakawan terhadap mahasiswa. hasil penelitian ini memberikan gambaran mendalam tentang kondisi literasi informasi mahasiswa, dan strategi intervensi yang diterapkan oleh pustakawan, dari pengembangan sesi pelatihan dengan layanan literasi informasi, kolaborasi dosen dengan melakukan pengajaran mata kuliah literasi dasar dan menjadi mata kuliah wajib, kemudian terakhir adalah memberikan umpan balik personal dengan mengadakan program klinik proposal yang memberikan nasehat atau solusi kepada pemustaka yang membutuhkan. temuan penelitian ini dapat memberikan wawasan berharga bagi perguruan tinggi dan pustakawan dalam merancang dan mengimplementasikan program literasi informasi yang efektif, menciptakan lingkungan akademik yang mendukung pengembangan keterampilan literasi informasi mahasiswa, serta meningkatkan kualitas pendidikan di era informasi.",0.514313

Query            : sangkut paut game dalam pendidikan
Processed Query  : sangkut paut game didik
Term ditemukan   : 3 term(s) dalam vocabulary.
Term di luar vocabulary: paut

,rank,id,title,abstract,cosine_similarity
0,1,2580-3662-111,game dalam upaya menaikkan citra perpustakaan di kalangan generasi strawbery,"penelitian ini membahas penggunaan game sebagai media untuk meningkatkan citra perpustakaan di kalangan generasi strawberry dan mengubah persepsinya terhadap perpustakaan. dengan memanfaatkan daya tarik game dan mengintegrasikan nilai-nilai literasi, pendidikan, dan interaktivitas, perpustakaan dapat menjadi tempat yang menarik dan edukatif. analisis menunjukkan bahwa game memiliki daya tarik universal bagi generasi strawberry yang terbiasa dengan teknologi dan hiburan digital. dengan desain yang tepat, game dapat menarik minat generasi ini, memungkinkan perpustakaan menjadi lebih sesuai dengan gaya hidupnya. pengintegrasian game ke dalam lingkungan perpustakaan atau gamifikasi memerlukan pendekatan holistik, termasuk dukungan teknis, pendidikan, dan promosi yang tepat. integrasi yang baik akan menciptakan pengalaman kohesif dan berkesinambungan bagi pengunjung. hasil penelitian ini menyimpulkan bahwa penggunaan permainan sebagai alat untuk meningkatkan citra perpustakaan memiliki potensi positif. dengan menggabungkan uniknya perpustakaan sebagai sumber literasi dengan daya tarik game, perpustakaan dapat menjadi tempat menarik, edukatif, dan inovatif bagi generasi muda, membantu nya mengembangkan keterampilan literasi dalam lingkungan yang interaktif dan menyenangkan.",0.460107
1,2,2685-7138-99,hubungan antara artikel mengenai game dan teknologi informasi pada scopus: studi bibliografi,"game sebagai media saat ini sudah diterapkan di beberapa bidang, termasuk pendidikan. implementasi permainan dalam pendidikan dikatakan mampu menawarkan metode pembelajaran yang inovatif dan efektif. di era baru ini, game sangat terkait dengan ilmu informasi. penelitian ini bertujuan untuk mengamati hubungan antara game dan ilmu informasi melalui artikel yang diindeks oleh scopus. penelitian ini adalah kualitatif dengan menggunakan metode blibliografi dalam mengumpulkan data. subjek adalah artikel di situs web scopus yang berisi ""permainan"" dan ""informasi sceince"". data dianalisis menggunakan vosviewer untuk mengungkap koneksi antara mereka. hasil penelitian menunjukkan bahwa antara subjek derek ada lebih banyak hasil breaoder yang dibagi menjadi beberapa sub-subjek. beberapa bagian subjek yang memiliki hubungan dengan informasi yang menjadi jembatan menunjukkan hubungan yang jelas tentang tren subjek sains, termasuk subjek permainan dalam keluarga sains informasi. dapat disimpulkan bahwa ada hubungan kutipan dan tren dalam menulis artikel ilmiah tentang game yang terkait dengan ilmu informasi.",0.403809
2,3,2715-274x-49,pengajaran literasi informasi dengan konsep gamification di perpustakaan perguruan tinggi,"game mungkin bukan hal yang baru bagi perpustakaan di indonesia. bentuk pemanfaatan game di perpustakaan di indonesia biasanya berupa quiz dalam kegiatan orientasi perpustakaan. namun sebenarnya aplikasi game di kegiatan perpustakaan bisa jauh lebih luas daripada itu, termasuk dalam kegiatan pengajaran literasi informasi. prinsip-prinsip game dapat digunakan untuk mengembangkan pengajaran literasi informasi agar kegiatan ini lebih menarik bagi pemustaka dan sekaligus membuat para pemustaka lebih terlibat aktif dalam proses pembelajaran. penerapan prinsip-prinsip game dalam kegiatan yang bukan merupakan kegiatan bermain ini dikenal dengan istilah gamification. gamification merupakan tren yang kian meluas dan kian mendapat tempat, tidak hanya di dunia pendidikan, pengembangan personal maupun dunia bisnis. mengingat manfaat yang bisa dipetik dari gamification, maka perpustakaan juga perlu belajar bagaimana mengaplikasikannya dalam dunia perpustakaan, terutama untuk pengembangan fungsi pendidikan, yakni pengajaran literasi informasi",0.373403
3,4,2502-6003-68,peningkatan pengetahuan “dampak negatif game online” melalui media poster pada siswa smpn 79 jakarta,"penelitian ini bertujuan untuk menganalisis ada tidaknya peningkatan pengetahuan tentang dampak negatif game online setelah diberikan edukasi dengan menggunakan media poster pada siswa smpn 79 jakarta. jenis penelitian ini adalah eksperimen menggunakan metode one-group pretest-posttest design. populasi dalam penelitian ini adalah siswa smpn 79 jakarta dengan jumlah sampel 72 responden. teknik sampling yang digunakan penelitian ini adalah sampling aksidental. uji t test menunjukkan sig (2-tailed) dengan hasil 0,000 < 0,05 maka h0 ditolak dan h1 diterima. dapat disimpulkan bahwa terdapat perbedaan sebelum dan sesudah diberikan edukasi dengan menggunakan media poster. hasil pre-test sebesar 57,50 sedangkan post-test sebesar 77,58. dengan demikian, siswa mengalami peningkatan pengetahuan tentang dampak negatif game online sebesar 20,08. oleh karena itu, dapat dikatakan bahwa media poster mampu meningkatkan pengetahuan siswa smpn 79 jakarta tentang dampak negatif game online.",0.260335
4,5,2797-9393-55,hubungan antara game dan pustakawan sebagai sarana edukasi pemustaka,"pustakawan berperan penting dalam meningkatkan literasi. program peningkatan literasi membutuhkan dana dan sumber daya yang tidak sedikit. permainan dapat menjadi sarana meningkatkan literasi pemustaka. studi ini bertujuan untuk mengobservasi sitasi serta katakata yang banyak digunakan pada abstrak dan judul penelitian terdahulu mengenai penggunaan game/permainan oleh para pustakawan. studi ini menggunakan metode kuantitatif bernama bibliometric untuk mengumpulkan dan menganalisis data. data diambil dari website scopus sebanyak 117 dari tahun 1981-2023. data dianalisis dengan menggunakan software r studio. hasil menunjukkan bahwa kebanyakan dokumen yang disitasi ditulis oleh penulis dari negara-negara eropa dan amerika serikat. namun, tidak ada satupun dari penelitian terdahulu tersebut yang disitasi oleh sesama penulis lokal. hasil diatas juga menunjukkan bahwa kata-kata yang sering digunakan baik pada judul maupun pada abstrak penelitian-penelitian terdahulu terdapat kata health/kesehatan.",0.224473
5,6,2301-8593-300,peningkatan minat baca remaja melalui perpustakaan desa kerano kuncoro untuk mengatasi kecenderungan remaja bermain game online,"keberadaan sumber-sumber informasi yang bermanfaat dan kontennya bisa dipertanggungjawabkan umumnya ada di perpustakaan. remaja seharusnya diarahkan untuk mau berkunjung secara rutin ke perpustakaan. upaya-upaya untuk mengarahkan remaja di desa agar mau memanfaatkan perpustakaan harus dilakukan oleh pustakawan secara serius. tujuan penelitian ini untuk menjelaskan bagaimana peningkatan minat baca remaja melalui perpustakaan desa kerano kuncoro untuk mengatasi kecenderungan remaja bermain game online. penelitian ini menggunakan pendekatan kualitatif. subjek penelitian ini adalah petugas perpustakaan desa kerano kuncoro dan pemustaka yang berstatus pelajar. proses pengumpulan data dilakukan menggunakan metode wawancara dan observasi. data yang diperoleh dianalisis secara kualitatif melalui tahap pengumpulan data, reduksi data, penyajian data dan penarikan kesimpulan. hasil yang didapatkan adalah: 1) kondisi ruangan perpustakaan kerano kuncoro cukup nyaman bagi pemustaka; 2) koleksi perpustakaan cukup lengkap dan beragam; 3) petugas perpustakaan sangat kooperatif terhadap pengungjung perpustakaan; 4) adanya layanan wifi gratis; 5) remaja termotivasi untuk mengunjungi perpustakaan desa secara rutin. peningkatan minat baca melalui perpustakaan desa untuk mengatasi kecenderungan game online sangat perlu. sebelum terjadinya pandemik covid-19, jumlah rata-rata pengunjung perhari antara 25-30 orang. dengan rata-rata kunjungan perhari minimal 2 jam otomatis akan mengurangi alokasi waktu mereka untuk bermain game online. peneliti menyarankan perlunya kerjasama antara perpustakaan desa dan pemerintah desa agar dapat menyelenggarakan program kegiatan yang unik dan menarik dan sebaiknya perpustakaan desa terus mencoba untuk melengkapi dan menyediakan koleksi yang up to date.",0.197269
6,7,2829-2707-6,pendidikan pemakai (user education) untuk optimalisasi layanan perpustakaan perguruan tinggi,"pemustaka perlu memiliki berbagai pengetahuan tentang dunia perpustakaan agar mampu memilih dan memilah informasi tersebut dengan baik, mampu mengenali kebutuhan informasi, dan mempunyai kecakapan atau kemampuan untuk mengakses sumber informasi. pendidikan pemakai adalah kegiatan yang dirancang untuk mendidik pemustaka agar mengetahui sumber-sumber informasi perpustakaan yang terdiri dari koleksi, fasilitas dan jasa perpustakaan, mendidik pemustaka dalam memanfaatkan sumber-sumber informasi secara tepat dan cepat serta mendidik pemustaka perpustakaan untuk menjadi pemustaka yang tertib dan bertanggung jawab. program pendidikan pemakai perlu dilaksanakan, karena kemampuan menggunakan perpustakaan merupakan dasar yang penting dalam mencapai keberhasilan dalam pendidikan. melalui pendidikan pemakai ini diharapkan pemustaka bisa lebih mandiri dalam memanfaatkan layanan di perpustakaan.",0.150671
7,8,2579-3160-12,pendidikan pemakai perpustakaan (di perpustakaan uin imam bonjol padang),"di dalam memanfaatkan perpustakaan tersebut, tidak semua mahasiswa baru memahami bagaimana cara menggunakan perpustakaan secara efektif dan efisien. oleh karena itu pihak perpustakaan sebaiknya mengadakan semacam bimbingan atau pendidikan pemakai perpustakaan untuk menuntun bagaimana mahasiswa menggunakan perpustakaan, dan fasilitas yang ada didalamnya.dari pendapat di atas dapat disimpulkan bahwa perpustakaan perguruan tinggi berfungsi sebagai sarana kegiatan belajar mengajar dalam mendukung pelaksanaan tri dharma perguruan tinggi dengan cara menyerbar luaskan informasi yang dimiliki. tugas perpustakaan perguruan tinggi adalah : melayani semua keperluan mahasiswa dari tingkat persiapan sampai kepada mahasiswa yang sedang menghadapi ujian sarjana dan menyusun skripsi, para staf dalam persiapan bahan perkuliaan serta para peneliti yang sedang bergabung dengan perguruan tinggi yang bersangkutan. dari pernyataan di atas dapat diketahui bahwa tugas perpustakaan perguruan tinggi adalahmelayani kebutuhan mahasiswa dan peneliti.",0.140127
8,9,2301-8593-116,meningkatkan efektivitas bimbingan pemakai melalui pembinaan kelompok pembaca pada perpustakaan perguruan tinggi (model pembelajaran pada mata kuliah metode penelitian antropologi),"salah satu tugas pokok pustakawan adalah melakukan bimbingan bagi pemakai perpustakaan. menurut petunjuk teknis jabatan fungsional pustakawan dan angka kreditnya, selanjutnya disebut petunjuk teknis, kegiatan ""melakukan bimbingan pemakai perpustakaan adalah kegiatan memberikan penjelasan tentang berbagai informasi perpustakaan yang bersangkutan dan penggunaan perpustakaan secara optimal kepada sekelompok pengguna baru perpustakaan",0.130346
9,10,2808-4659-4,pengembangan perangkat lunak pengujian instrumen asesmen pembelajaran,"penelitian ini didasari ide menjadikan universitas pendidikan ganesha menjadi pusat transaksi informasi pendidikan, paling tidak untuk wilayah bali dan sekitarnya. mahasiswa universitas pendidikan ganesha datang dari berbagai daerah. bahkan untuk program pascasarjana, mahasiswa ada yang berstatus dosen, guru, kepala sekolah, pengawas sekolah, pengelola lembaga pendidikan, tenaga kependidikan . mahasiswa tersebut merupakan agen-agen perubahan yang handal di bidang pendidikan, sehingga memiliki peran yang amat strategis dalam pembinaan pendidikan nasional. universitas pendidikan ganesha telah memiliki portal web e-learning sebagai media pertukaran informasi pendidikan. portal tersebut sudah dilengkapi dengan berbagai materi dari para dosen atau bahkan mahasiswa. bila portal web tersebut dilengkapi dengan fasilitas layanan lain yang diperlukan dunia pendidikan, seperti perangkat lunak pengujian instrumen penelitian kuantitatif, maka peran universitas pendidikan ganesha sebagai pusat transaksi informasi pendidikan semakin lengkap. penelitian ini akan menghasilkan perangkat lunak pengujian instrumen penelitian kuantitatif yang dapat digunakan oleh guru, mahasiswa calon guru, atau praktisi pendidikan lainnya. perangkat lunak ini dapat digunakan dengan mudah, dan bahkan pemakai tidak harus memiliki kemampuan evaluasi yang memadai. hasil pengujian yang diberikan mencakup validitas instrumen, reliabilitas instrumen, serta perhitungan lain yang dipandang perlu. instrumen yang diuji dapat berupa instrumen dikotomi atau politomi",0.128246

Query            : dampak pandemi covid-19 terhadap pendidikan
Processed Query  : dampak pandemi covid didik
Term ditemukan   : 4 term(s) dalam vocabulary.

,rank,id,title,abstract,cosine_similarity
0,1,2775-8761-38,dampak rendahnya perpustakaan di masa pandemi covid-19 pada siswa smpn 2 raha,"masalah yang dihadapi sekolah saat ini adalah masa pandemic covid 19 yang menghambat proses strategi perpustakaan sekolah hampir tidak ada yang menyangka, wajah pendidikan akan berubah drastis akibat pandemi covid 19. penelitian ini bertujuan untuk mengetahui dampak rendahnya pemanfaatan perpustakaan pimasa pandemi covid-19 pada siswa smpn 2 raha. metode penelitian yang digunakan adalah deskripsi kualitatif, informan dalam penelitian sebanyak lima orang. teknik pengumpulan data dilakukan dengan melalui observasi, wawancara dan dokumentasi. hasil penelitian ini menunjukkan bahwa dampak rendah pemanfaatan perpustakaan di masa pandemi covid-19 pada smpn 2 raha ada beberapa dampak sesuai dengan menurut sutarno (2003). dampak rendahnya pemanfaatan perpustakaan di masa pandemi covid-19 ada 4 dampak yaitu pemeliharaan bahan pustaka, kebersihan perpustakaan, kerapian koleksi, penataan koleksi. pengelola perpustakaan dan pemustaka merasa tehalang dengan adanya covid-19 sehingga mereka tidak bisa menata perpustakaan dengan baik dan pengunjung juga tidak bisa berkunjung ke perpustakaaan seperti biasanya. penelitian ini diharapkan dapat menjadi rujukan sebagai bahan informasi bagi peneliti selanjutnya yang akan meneliti topik yang berkaitan dengan dampakrendanya pemanfaatan perpustakaan di masa pandemi covid-19.",0.590535
1,2,2685-7138-94,wacana pandemi covid-19 terhadap penutupan perpustakaan,"coronavirus disease (covid-19) telah ditetapkan statusnya sebagai pandemi oleh who karena penyebarannya ke berbagai negara dalam waktu yang sama. perpustakaan pun tidak luput dari dampak wacana pandemi covid-19 karena harus ditutup sebagai upaya yang dilakukan secara bersama-sama dalam memutus rantai penyebaran covid-19. melalui studi literatur terutama dari jurnal ilmiah, penulis mencoba mengumpulkan berbagai informasi terkait dengan penutupan perpustakaan dikarenakan krisis, untuk kemudian dapat diketahui hal-hal yang dapat dilakukan perpustakaan di tengah pandemi covid-19. hasil studi menunjukkan selama masa pandemi covid- 19 perpustakaan harus menentukan kebijakan terkait layanan seperti buka atau tidak dan pembebasan denda. perlunya mempertimbangkan mengenai tindakan disinfektan terhadap gedung dan koleksi secara keseluruhan. perpustakaan harus menjadi pusat informasi tepercaya sebagai upaya memperlambat penyebaran virus dan informasi yang salah. perpustakaan juga seyogyanya menyediakan sumber informasi yang dapat diakses pemustaka melalui electronic resources. perpustakaan dan pustakawan selama masa pandemi dapat terlibat sebagai gugus tugas covid-19 yakni gedung perpustakaan dapat digunakan sebagai gudang logistik untuk pendistribusian masker, alat uji dan alat pelindung diri (apd). terakhir, perpustakaan dapat mengadakan program yang bermanfaat untuk pemustaka melalui konsep layanan “boutique” dan webinar. hasil studi dapat dijadikan panduan dan lesson learned ke depannya untuk dapat diterapkan oleh perpustakaan dan pustakawan saat masa krisis.",0.451114
2,3,2685-8363-130,peran teknologi informasi dalam layanan online perpustakaan masa pandemi covid-19,"pandemi covid-19 telah menyerang berbagai lapisan masyarakat dari seluruh belahan dunia, termasuk indonesia. banyak di antara masyarakat yang terkena dampak covid-19 mulai beradaptasi terhadap keadaan baru tersebut dengan berbagai cara. perpustakaan sebagai sumber informasi dituntut untuk menyesuaikan kebutuhan pada pemustakanya. penulis menggunakan studi literatur atau kajian pustaka dalam menyusun tulisan ini. peran teknologi di masa pandemi memberikan kemudahan dalam memanfaatkan perpustakaan. pustakawan melakukan adaptasi layanan melalui online seperti: layanan konsultasi, layanan penelusuran sumber digital, layanan pengecekan plagiarism, dan membangun digital library. peran teknologi di perpustakaan dalam memberikan layanan selama pandemi covid-19 membutuhkan keahlian pustakawan dalam memahami alat yang digunakan. media zoom, google meet, whatsapp, youtube, instagram, website perpustakaan sangat diperlukan dalam diseminasi informasi. tujuan dari penulisan ini adalah untuk menjelaskan bagaimana peran teknologi informasi terutama dari layanan online di perpustakaan supaya bisa memenuhi kebutuhan informasi penggunanya. hasil dari penulisan ini dapat disimpulkan bahwa perpustakaan mempunyai peranan penting dalam menyebarkan informasi melalui peran teknologi di masa pandemi covid-19.",0.439370
3,4,2477-0361-215,tinjauan literatur sistematis tentang tren penelitian penyebaran hoax selama pandemi covid-19 di indonesia,"pendahuluan. kesadaran mengenai penyebaran hoax melalui media di masa pandemi covid-19 di indonesia harus mendapat perhatian khusus. metode penelitian. metode tinjauan literatur sistematis dengan pendekatan kualitatif. tinjauan dilakukan terhadap literatur yang tersedia di database google scholar, garuda ristekbrin, dan research gate terkait penyebaran hoax melalui media selama pandemi covid-19. proses eksklusi dengan beberapa tahap menghasilkan 20 karya ilmiah untuk ditinjau. data analisis. grafik dan tabel yang digunakan untuk mensistematisasikan informasi yang paling relevan dengan topik penelitian. hasil dan pembahasan. penyebaran hoax dilakukan melalui media selama pandemi covid-19 pada rentang waktu 2020-2021 di indonesia. tiga pertanyaan penelitian antara lain kuantitas terbitan mengenai penyebaran hoax melalui media di masa pandemi covid-19 di indonesia dalam rentang waktu 2020-2021, fokus dari penelitian-penelitian tersebut, dan metodologi yang digunakan dalam penelitian. berdasarkan hasil temuan, diperoleh 20 karya ilmiah yang membahas seputar penyebaran hoax selama masa pandemi covid-19, dengan minor topik antara lain identifikasi berita hoax seputar covid-19 di media sosial, perilaku informasi di media sosial saat pandemi covid-19, dan strategi menghadapi atau menanggulangi penyebaran hoax di masa pandemi. kesimpulan dan saran. terdapat karya ilmiah mengenai penyebaran hoax melalui media selama pandemi covid-19 di indonesia dan ini perlu mendapatkan perhatian. kata kunci: hoax; covid-19; tinjauan literatur sistematis",0.407119
4,5,2549-1334-136,covid-19 pandemic publication during 2020 in indonesia (a bibliometrics study),"covid-19 dinyatakan sebagai wabah pandemi oleh who sejak awal tahun ini. di indonesia sendiri, pernyataan resmi dari pemerintah bahwa covid-19 telah masuk ke negara ini adalah pada maret 2020. sejak itu, wabah ini menjadi isu yang banyak dikaji dari berbagai disiplin ilmu. penelitian ini menggambarkan tren perkembangan publikasi jurnal di indonesia; kolaborasi penulis, bentuk publikasi, dan sebaran disiplin ilmu. data penelitian diperoleh melalui garuda (garba rujukan digital) dari bulan maret hingga akhir oktober 2020 di mana terdapat sebanyak 326 publikasi jurnal bertemakan pandemi covid-19. dengan bantuan ms. excel, data dianalisis menggunakan statistik sederhana. hasil penelitian ini menemukan bahwa terdapat 688 penulis secara total, baik penulis individu maupun penulis gabungan dari ke 326 publikasi jurnal. tingkat kolaborasi penulis adalah 0,561 atau sebesar 56,1%, hal ini menunjukkan bahwa artikel yang ditulis kolaboratif lebih banyak daripada ditulis secara individu. bentuk publikasi banyak yang merupakan artikel hasil penelitian dibandingkan dengan kajian literatur bertema pandemi covid-19. tiga bidang ilmu yang paling banyak memublikasikan tema pandemi covid-19 ialah pendidikan, hukum, dan kesehatan",0.402567
5,6,2685-7138-43,optimalisasi layanan online perpustakaan nasional di masa pandemi covid-19,"pandemi covid-19 memberi dampak yang sangat besar bagi masyarakat tidak terkecuali perpustakaan. penerapan pembatasan aktivitas fisik di luar rumah merupakan tantangan sekaligus peluang tersendiri bagi perpustakaan untuk tetap memberikan pelayanan kepada masyarakat. dengan berbagai keterbatasan, perpustakaan dituntut untuk berinovasi dalam melayani pemustaka agar tetap dapat memberikan layanan prima. kajian ini bertujuan untuk mengetahui inovasi serta pemanfaatan layanan online perpustakaan nasional ri di masa pandemi. melalui optimalisasi layanan digital perpustakaan nasional telah memberikan akses seluas-luasnya untuk seluruh masyarakat indonesia atas bahan bacaan yang beragam dan berkualitas. pandemi covid-19 membatasi gerak masyarakat, namun perpustakaan terbukti dapat memperluas ruang gerak tersebut secara virtual.",0.399541
6,7,2829-2707-84,layanan perpustakaan pasca covid-19 di perpustakaan pusat dan fakultas peternakan universitas gadjah mada,"kondisi pandemi covid-19 sebagai kondisi darurat kesehatan masyarakat di seluruh dunia, diperlukan mitigasi kebencanaan akan ketersediaan literatur tentang pandemi dan dampaknya terhadap perpustakaan akan terus meningkat. tulisan ini membahas proses tahun terakhir 2021 hingga september 2022 dalam mengembangkan layanan perpustakaan yang sederhana dan memberi gambaran yang lebih luas tentang program dan inisiatif kegiatan pustakawan sebelum, selama, dan pandemi covid-19 normal (november 2021–september 2022). program dan inisiatif kegiatan pustakawan selama pandemi menunjukkan bahwa karakteristik akses ruang yang dibatasi oleh langkah-langkah keamanan protokol kesehatan, digitalisasi koleksi, dan layanan online. penulisan ini juga mengkaji inisiatif dan program tahun sebelumnya serta membahas prosedur “new normal” tahap selanjutnya. tulisan ini akan memberikan wawasan tentang bagaimana perpustakaan pusat ugm dan perpustakaan fakultas peternakan ugm menanggapi pandemi baru-baru ini, dan menginformasikan aktivitas perpustakaan dan upaya untuk lebih siap mengambil tindakan penting, cepat, dan tegas di era pasca-covid-19",0.381250
7,8,2579-3160-67,pelayanan perpustakaan sekolah selama masa pandemi covid-19,"pandemi covid-19 telah berlangsung selama kurang lebih delapan bulan lamanya di negara indonesia. berbagai kegiatan yang seharusnya dapat dilaksanakan secara langsung, harus dialihkan menjadi kegiatan daring, ditunda, atau bahkan ditiadakan terlebih dahulu. kebijakan pemerintah yang mengharuskan pelaksanaan pembatasan sosial berskala besar pada masa awal menyebarnya covid-19 di indonesia mengharuskan berbagai lembaga ditutup, termasuk lembaga pendidikan formal atau sekolah serta perguruan tinggi. kebijakan mendadak tersebut memberikan berbagai macam hambatan yang cukup besar dalam berbagai aspek. salah satu bagian yang juga harus menerima hambatan tersebut adalah perpustakaan. perpustakaan yang berada di sekolah merupakan salah satu bagian yang ikut serta dalam proses penyebaran informasi dan ilmu pengetahuan di lingkungan sekolah. layanan perpustakaan yang semula dapat dilaksanakan secara langsung dan leluasa, harus dialihkan kepada berbagai alternatif atau bahkan diberhentikan terlebih dahulu. proses layanan sirkulasi yang terhambat mengharuskan pustakawan untuk memikirkan cara lain untuk memastikan kembali bahan pustaka yang dipinjam oleh pemustaka telah dikembalikan atau belum. selain hal tersebut, selama masa pandemi covid-19 pemanfaatan media sosial juga menjadi salah satu jalan agar pelayanan di perpustakaan dapat terus dijalankan. dengan adanya pandemi covid-19 juga, kegiatan yang telah direncanakan jauh-jauh hari juga harus dipikirkan kembali oleh pihak-pihak yang bersangkutan dalam proses penyelenggaraannya. adaptasi pada kebiasaan baru juga ternyata telah menghasilkan berbagai inovasi di tengah-tengah masyarakat. meski begitu, kegiatan yang dialihkan menjadi kegiatan daring juga menjadi salah satu alternatif yang dapat dipilih oleh masyarakat agar dapat menekan angka penyebaran covid19 di indonesia",0.379509
8,9,2829-4920-23,analisis strategi komunikasi layanan perpustakaan universitas riau di era pandemi covid 19,"pandemi covid-19, telah merubah seluruh tatanan kehidupan, dan telah memaksa seluruh perpustakaan untuk melakukan inovasi agar tetap eksis dengan menerapkan strategi komunikasi perpustakaan. penelitian ini bertujuan untuk mengetahui bagaimana strategi komunikasi perpustakaan universitas riau pada masa pandemi covid-19. metode yang diganakan adalah metode kualitatif dengan pendekatan deskriptif. teknik pengumpulan data dilakukan dengan wawancara, observasi, dokumentasi, dan studi literatur. wawancara dilakukan terhadap tiga informan interen perpustakaan ditambah empat informan eksteren dari kalangan mahasiswa. analisis data dilakukan dengan tahapan reduksi data, display data, dan terakhir verifikasi data. hasil penelitian menunjukkan bahwa strategi komunikasi perpustakaan universitas riau pada masa pandemi covid-19 meliputi tiga hal, yaitu: 1) menjalankan program yang sudah ada, 2) melakukan pengembangan aplikasi untuk pelayanan berupa e-form, mengoptimalkan pemanfaatan sosial media dalam komunikasi dan penyebaran informasi. 3) melakukan pengurangan sanksi. simpulan penelitian ini adalah bahwa strategi komunikasi layanan yang dilakukan pada masa pandemic covid-19 di perpustakaan universitas riau dapat memberikan dampak positif terhadap pemenuhan kebutuhan informasi pemustaka.",0.377759
9,10,2443-0293-66,inovasi peningkatan pelayanan perpustakaan universitas pendidikan indonesia dalam menghadapi pandemi covid-19,"pandemi covid-19 memberikan dampak kepada setiap kegiatan dan aspek kehidupan masyarakat, termasuk kegiatan pelayanan perpustakaan. akibat kebijakan pemerintah, perpustakaan tidak dapat melayani penggunanya secara langsung dan harus memanfaatkan perkembangan teknologi informasi dan komunikasi dalam pelayanannya. perpustakaan perguruan tinggi harus melakukan inovasi untuk tetap melayani kebutuhan penggunanya di masa pandemi. tujuan dari penelitian ini adalah untuk mengetahui inovasi yang dilakukan oleh perpustakaan perguruan tinggi universitas pendidikan indonesia dalam menghadapi pandemi covid-19. penelitian dilakukan dengan metode kualitatif dan data diperoleh dari hasil wawancara tidak langsung melalui media whatsapp dengan pustakawan universitas pendidikan indonesia dan observasi terhadap website perpustakaan universitas pendidikan indonesia. analisis data dengan menggunakan metode deskriptif dari hasil data yang didapatkan. penelitian mendapatkan hasil, inovasi yang dilakukan perpustakaan universitas pendidikan indonesia adalah dengan mengoptamilisasi pelayanan perpustakaan secara online atau dalam jaringan melalui digital library pada website upi center library yang menyediakan bermacam layanan dan koleksi elektronik yang bisa diakses oleh seluruh masyarakat. agar pelayanan dapat digunakan dengan maksimal oleh pengguna, perpustakaan upi meningkatkan strategi pemasaran menggunakan media sosial. meskipun pelayanan perpustakaan tidak dapat dilakukan secara luar jaringan akibat kebijakan pemerintah untuk mengurangi penyebaran corona virus, namun dengan inovasi optimalisasi pelayanan daring melalui perpustakaan digital, pelayanan perpustakaan dapat tetap dimanfaatkan dengan maksimal.",0.374477